INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Jacobo','Millan','jmillan@nalandaglobal.com','2018-11-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Sofia','Gonzalez','sgonzalez@nalandaglobal.com','2018-11-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Ana','De Palma','vdepalma@nalandaglobal.com','2018-11-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Ignacio','Arjona','iarjona@nalandaglobal.com','2018-11-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('David','Hidalgo','dhidalgo@nalandaglobal.com','2018-11-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Ascension','Castro','acastro@nalandaglobal.com','2018-11-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Javier','Esquivias','jesquivias@nalandaglobal.com','2018-11-07');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Alba','Martin','amartin@nalandaglobal.com','2018-11-08');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Jesus','Gomez','jgomez@nalandaglobal.com','2018-11-09');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Jesus','Ciriano','jciriano@nalandaglobal.com','2018-11-10');
